---
title: "Introduction to Probability"
author: "Adejumo Ridwan Suleiman"
format: revealjs
---

# What is a Probability Distribution?

## What is a Probability Distribution?

- Distribution of the probability of all possible outcomes of a random variable

- Arrangement of the events and their corresponding probabilities in a tabular form

## What is a Probability Distribution? - Example

In a family of 4 children at a community, what is the distribution of the number of boys?

| $X$ | 0 | 1 | 2 | 3 | 4 |
| --- | --- | --- | --- | --- | --- |
| $P(x)$ | 0.413 | 0.236 | 0.211 | 0.090 | 0.05 |


# Terms and Terminologies

## Terms and Terminologies

- **Random Variable**: A variable  represents outcomes of a random process, that can either be discrete or continous.

- **Probaility Distributions**: Describes how probability is distributed over possible outcomes.

- **Probability Mass Function**: This is the given probability that a discrete random variable is exaclty equal to some value, and is used with discrete random variables

- **Probability Density Function**: This is the given probability of a random variable falling within a specific range of values, rather than a singl value. It is used for continous random variables.

- **Cumulative Distribution Function**: This is the probability tthat a random variable takes a value less that or equal to a certain value. It is the cumlative sum of probabilities for discrete variables and the integral of the PDF for contnous variables.

 - **Expected Vallue**: This is the long run average o outtcomes of a random varrible. Whih is also the average of all possible valuess that the random varible can take.

# Types of Probability Distribution

## Discrete Probability Distributtions

- Bernoulli Distribution
- **Binomial Distribution**
- **Poisson Distribution**
- Geometric Distribution
- Negative Binomial Distribution



## Contnous Probability Distributions

- **Normal (Gaussian) Distribution**
- Uniform Distribution
- Exponential Distribution
- Gamma Distribution
- Beta Distribution


# Binomial Distribution

## Definition

- If you have only two possible outcomes in $n$ independent number of trials, then the probability of exactly $X$ successes.

$P(X=x) = {n\choose x}p^x(1-p)^{n-x}$

- The total number of successes $X$ is a binomial variable with parameters $n$ and $p$.

  - where $n$ is fixed number of trials and
  - each trial results in a "success" with profitability $p$ and a "failure" with probability $(1-p=1)$.
  
## Properties

- Trial has only two possibl outcomes.
- Trials repeated "n" times.
- Successive trials are independent.
- Probability of success is constant from trial to trial.
- The random variable $X$ is the number of successes in the $n$ trials.

## Mean and Variance

$$
\mu = np \\
\sigma = np(1-p)
$$


# Poisson Distribution


# Normal Distribution

